# Generated by Django 4.0.4 on 2022-05-31 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enseignant', '0002_rename_code_enseignant_prenom'),
        ('matiére', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='enseignant_matire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Enseignant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enseignant.enseignant')),
                ('id_Matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matiére.matiere')),
            ],
        ),
    ]
