# Generated by Django 4.0.4 on 2022-06-02 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enseignant', '0002_rename_code_enseignant_prenom'),
        ('matiére', '0001_initial'),
        ('enseignant_matiere', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='enseignant_matire',
            new_name='enseignant_matiere',
        ),
    ]
