# Generated by Django 4.0.4 on 2022-05-31 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filiére', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(null=True)),
                ('id_Filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filiére.filiere')),
            ],
        ),
    ]
