# Generated by Django 4.0.4 on 2022-05-31 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('type', '0001_initial'),
        ('filiére', '0001_initial'),
        ('matiére', '0001_initial'),
        ('semestre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='matiereSemestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.IntegerField()),
                ('id_Filiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filiére.filiere')),
                ('id_Matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matiére.matiere')),
                ('id_Semestre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='semestre.semestre')),
                ('id_Type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='type.type')),
            ],
        ),
    ]
