# Generated by Django 4.0.4 on 2022-06-02 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filiére', '0002_alter_filiere_id'),
        ('type', '0001_initial'),
        ('matiére', '0001_initial'),
        ('semestre', '0001_initial'),
        ('matiere_semestre', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='matiereSemestre',
            new_name='matiere_semestre',
        ),
    ]
