# Generated by Django 4.0.4 on 2022-05-31 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filiere',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
