# Generated by Django 4.0.4 on 2022-06-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='debut',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
