# Generated by Django 4.0.4 on 2022-06-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_alter_cours_debut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='debut',
            field=models.DateTimeField(null=True),
        ),
    ]
