# Generated by Django 4.0.4 on 2022-06-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_alter_cours_debut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='id_Enseignant',
            new_name='Enseignant',
        ),
        migrations.RenameField(
            model_name='cours',
            old_name='id_Filiere',
            new_name='Filiere',
        ),
        migrations.RenameField(
            model_name='cours',
            old_name='id_Groupe',
            new_name='Groupe',
        ),
        migrations.RenameField(
            model_name='cours',
            old_name='id_Matiere',
            new_name='Matiere',
        ),
        migrations.RenameField(
            model_name='cours',
            old_name='id_Salle',
            new_name='Salle',
        ),
        migrations.RenameField(
            model_name='cours',
            old_name='id_Type',
            new_name='Type',
        ),
    ]
