# Generated by Django 4.0.4 on 2022-06-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salle',
            name='pc',
            field=models.IntegerField(null=True),
        ),
    ]
