# Generated by Django 4.0.4 on 2022-05-31 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=11)),
                ('capacite', models.IntegerField()),
                ('id_classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classe.classe')),
            ],
        ),
    ]
